### ISSUE TITLE
Want v1.1 on Homebrew

### ISSUE THREAD

**Issue by qnighy** [creasty/dor#19]
The README here instructs to use Homebrew to install rid, but [v1.1 doesn't seem to be released there](https://github.com/creasty/homebrew-tools/blob/6ea2c4075b0e1035c841b4337b23bc709f1cf655/Formula/rid.rb#L2).

**Comment by creasty** [comment]
Forgotten to do that. Will do...

Much appreciated if you could submit PRs 😓
https://github.com/creasty/homebrew-tools
